apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
# először dekódolni kell a https://github.com/devopshydclub/vprofile-project.git
# vp-docker branchon lévő /src/main/resources/application.properites fileban található bdbc.password értéket
  db-pass: dnByb2RicGFzcw==
  rmq-pass: Z3Vlc3Q=
